// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sloth.Infrastructure.DatabaseContext;

#nullable disable

namespace Sloth.Infrastructure.Migrations
{
    [DbContext(typeof(SlothDbContext))]
    [Migration("20240930152003_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sloth.Domain.Entities.CookieKey", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "Key", "ExpirationDate");

                    b.ToTable("CookieKey");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.EndpointConfiguration", b =>
                {
                    b.Property<string>("EndpointID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.HasKey("EndpointID");

                    b.ToTable("EndpointConfiguration");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.FailedAttempt", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("FailedAttempt");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.Language", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageCode");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.LockedPassword", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LockExpiration")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "PasswordHash");

                    b.ToTable("LockedPassword");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.LockedUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LockExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.ToTable("LockedUser");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "Token", "ExpirationDate");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.SecurityTable", b =>
                {
                    b.Property<string>("SecurityTableID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ControlID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserGroup")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("SecurityTableID", "ControlID", "UserGroup");

                    b.HasIndex("SecurityTableID", "ControlID");

                    b.ToTable("SecurityTable");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.SystemOption", b =>
                {
                    b.Property<string>("OptionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OptionID");

                    b.ToTable("SystemOption");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.Theme", b =>
                {
                    b.Property<int>("ThemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThemeID"));

                    b.Property<string>("BackGroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformationColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeutralColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuccessColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThemeID");

                    b.ToTable("Theme");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.Translation", b =>
                {
                    b.Property<string>("ENUText")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ENUText", "LanguageCode");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ThemeID")
                        .HasColumnType("int");

                    b.Property<string>("UserImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("GroupID");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("RoleID");

                    b.HasIndex("ThemeID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.Validation", b =>
                {
                    b.Property<string>("ValidationName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValidationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValidationName");

                    b.ToTable("Validation");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.WebControl", b =>
                {
                    b.Property<string>("PageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ControlID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ControlLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlPlaceholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlTooltip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutePageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityTableID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageID", "ControlID");

                    b.ToTable("WebControl");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.WebControlValidation", b =>
                {
                    b.Property<string>("PageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ControlID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PanelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageID", "ControlID");

                    b.ToTable("WebControlValidation");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.WebPage", b =>
                {
                    b.Property<string>("PageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityTableID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageID");

                    b.ToTable("WebPage");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.WebPageSecurity", b =>
                {
                    b.Property<string>("PageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserGroup")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CanAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CanAdd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CanDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PageID", "UserGroup");

                    b.ToTable("WebPageSecurity");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.CookieKey", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.FailedAttempt", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.LockedPassword", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.LockedUser", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.SecurityTable", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.WebPage", null)
                        .WithMany()
                        .HasForeignKey("SecurityTableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.User", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.UserGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sloth.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sloth.Domain.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sloth.Domain.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sloth.Domain.Entities.WebControl", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.WebPage", null)
                        .WithMany()
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.WebControlValidation", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.WebControl", null)
                        .WithMany()
                        .HasForeignKey("PageID", "ControlID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sloth.Domain.Entities.WebPageSecurity", b =>
                {
                    b.HasOne("Sloth.Domain.Entities.WebPage", null)
                        .WithMany()
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
