@Sloth.API_HostAddress = https://localhost:7180
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBRE1JTiIsImp0aSI6ImViNjYyNDUyLWQ4YWYtNGQ5Ni05Y2IyLWE2YmI2MzlhMTM1MSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiOTlmZTg2ODgtZGRmZC00OGQ3LWFiZDctYjljZGJiNzI3YTEzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5AdGVzdC5jb20iLCJleHAiOjE3MjYzNzExMDUsImlzcyI6IlRlc3QiLCJhdWQiOiJUZXN0In0.u5y6TcoJbtO5Y1pVMGRoS44GUds1ba_BZJKXIOIdrEs

POST {{Sloth.API_HostAddress}}/api/auth/RegisterUser
Content-Type: application/json

{
  //RegisterUserCommand
}

###

GET {{Sloth.API_HostAddress}}/api/uielements/TestAuth
Authorization: Bearer {{Token}}
###

POST {{Sloth.API_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "login": "KRZMAS",
  "password": "master"
}

###