@Sloth.API_HostAddress = https://localhost:7180
@Token = CfDJ8O8IacqVoftHkBu-cS-u6S27sB9AZdxf1sy7IFPLoAku_VViSED08gVuDuu-OL9pNrD3hDUhPORPdXCz1D63ICqN4TeCr2SFmvVqnQDCnttE2b_rGGTxn80fQg3DCcRGXhucgIzOCBDd5xrum6YiAc4SRtjgMzDwq5PE4ycQpHW5WYNbS2FcXItxN1oCmcKXUChNRai5GTgPV6HyyZi90Hy3fLVNCPGhw9znxRKRinhs3gn0cZwSrIchz-orK7mLrBp7TmqQxZHnVDKK9Oe271bYY632vjNQPpiq1zpRFiopDDqLgpapap9HapY-56vHsXWx533wwH94GtQeCYvyWzXiy0xx0vHp3HEUBPyLcbhXO7iuh3FNNVpzDeeP6-mdlEHyzQ-P2_5J_uDZy3obbdcps94VX_wjJsb_KUeMJIvqQ9uZt-GaHkTMfkAwRbLOcCgWMhgmp-bLOg1gVFeVR-piy3e2CMHx_AIIAIJ6gBZ3HX-SSXSzLgKoHJMZ9gZD7gw8JvxmhkcDO9Dm4JAeWh_wVDD-3ZWuyQD9g8byZIThg1OQ18ut0-tb9DWw1p43VEoMrtz8GWy69o5p99ZacVImN0dZKabnusbe_0a-nNsQ_vvRzJCQdEknbOkDzm0PlHRYptpXhtYqY_92RJZGGMliLTg0SPm2p1QbhEWYBDCpV6V3iB7mZk9u6HPSKHeWvEf10nryxkbYFidpBC7IvhvAzjyIpqoe-TM3bFeCXaAH7tP0dUihk2PLT--x8Ax4VdBnqdTAVeV9yGUyNJXLZYAn07CS_B9GvK1UVBgjPEyM4dCggC0GXvEPIZ5iOhhIRflYgRmn6KlZ9DYIZl1JZ-I


POST {{Sloth.API_HostAddress}}/api/auth/Login
Content-Type: application/json
{
  "login": "KRZMAS",
  "password": "master"
}

###

GET {{Sloth.API_HostAddress}}/api/uielements/GetWebPage
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "PageID": "MainPage"
}
###

GET {{Sloth.API_HostAddress}}/api/uielements/GetMainWebPage
Authorization: Bearer {{Token}}

POST {{Sloth.API_HostAddress}}/api/auth/Register
Content-Type: application/json

{
  //RegisterCommand
}

###

POST {{Sloth.API_HostAddress}}/api/auth/Login
Content-Type: application/json

{
  //LoginCommand
}

###
